#!/usr/bin/env python3
"""Downloads flat country flags (flagcdn.com / Flagpedia, public domain) into the app.

Writes res/drawable-nodpi/flag_<code>.webp for every ISO 3166-1 alpha-2 code and generates
ui/FlagAssets.kt: the hard-coded map from country code to drawable.

Usage: python3 scripts/fetch_flags.py
"""
import json
import os
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "app", "src", "main", "res", "drawable-nodpi")
KT = os.path.join(ROOT, "app", "src", "main", "java", "app", "borderless", "ui", "FlagAssets.kt")
WIDTH = 160


def main():
    os.makedirs(RES, exist_ok=True)
    codes = json.load(urllib.request.urlopen("https://flagcdn.com/en/codes.json"))
    countries = sorted(c for c in codes if len(c) == 2)
    for code in countries:
        dst = os.path.join(RES, f"flag_{code}.webp")
        if not os.path.exists(dst):
            urllib.request.urlretrieve(f"https://flagcdn.com/w{WIDTH}/{code}.webp", dst)
    entries = "\n".join(f'        "{c.upper()}" to R.drawable.flag_{c},' for c in countries)
    with open(KT, "w") as f:
        f.write(f"""package app.borderless.ui

import app.borderless.R

// Generated by scripts/fetch_flags.py — do not edit by hand.
// Flags: flagcdn.com (Flagpedia), public domain.

/** Country code (ISO 3166-1 alpha-2) to its flag drawable. */
object FlagAssets {{
    val byCode: Map<String, Int> = mapOf(
{entries}
    )
}}
""")
    total = sum(os.path.getsize(os.path.join(RES, f)) for f in os.listdir(RES) if f.startswith("flag_"))
    print(f"{len(countries)} flags, {total / 1024:.0f} KB")


if __name__ == "__main__":
    main()
